### ISSUE TITLE
Travis build fails to upload to Anaconda Cloud

### ISSUE THREAD

**Issue by jdblischak** [conda-forge/r-lmertest-feedstock#2]
The R 3.4.1 build for osx-64 is able to build successfully. However, after multiple restarts, it always fails at the upload stage. The recipe has been recently rerendered (see #1), so it should be up-to-date.

The only slightly strange thing I noticed is that the merge commit only triggered a build for AppVeyor.

Any ideas @bgruening?

https://travis-ci.org/conda-forge/r-lmertest-feedstock/jobs/340827023#L579

```
The command "conda build ./recipe" exited with 0.
3.00s$ upload_or_check_non_existence ./recipe conda-forge --channel=main
Using Anaconda API: https://api.anaconda.org
Processing r-lmertest
Using Anaconda API: https://api.anaconda.org
Traceback (most recent call last):
  File "/Users/travis/miniconda3/bin/upload_or_check_non_existence", line 135, in <module>
    main()
  File "/Users/travis/miniconda3/bin/upload_or_check_non_existence", line 124, in main
    upload(cli, meta, owner, channel)
  File "/Users/travis/miniconda3/bin/upload_or_check_non_existence", line 75, in upload
    env=os.environ)
  File "/Users/travis/miniconda3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['anaconda', '--quiet', '-t', '/var/folders/vy/rcv48w3j4w79llzf_x6qnvw40000gn/T/tmp3ghpk7c3/binstar.token', 'upload', '/Users/travis/miniconda3/conda-bld/osx-64/r-lmertest-2.0_33-r3.4.1_0.tar.bz2', '--user=conda-forge', '--channel=main']' returned non-zero exit status 1.
```

**Comment by jdblischak** [comment]
@ocefpaf Could you please also send an empty commit to this feedstock? When it was rerendered in #1, for some reason the Travis "push" job was triggered for the PR. Then when it was merged, only the AppVeyor build was activated. I've tried restarting the Travis build multiple times, but it always fails to upload to Anaconda (and I'm guessing it is related to the fact that the build was originally started for the PR).

**Comment by ocefpaf** [comment]
There was a CI skip in that commit. Maybe it is better to send a new PR. Let me try.

**Comment by ocefpaf** [comment]
#5 seems to have fixed it.

**Comment by jdblischak** [comment]
Thanks @ocefpaf!
